spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:h2:mem:todolist
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081
  servlet:
    context-path: /todolist